version: '2'
services:
    plantmall-app:
        image: plantmall
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://plantmall-mysql:3306/plantmall?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    plantmall-mysql:
        extends:
            file: mysql.yml
            service: plantmall-mysql
